### ISSUE TITLE
 `create_task_id()` for horizon returns an error if required and optional set to NULL 

### ISSUE THREAD

**Issue by LucieContamin** [Infectious-Disease-Modeling-Hubs/hubAdmin#4]
I have a [tasks.json ](https://github.com/midas-network/flu-scenario-modeling-hub/blob/main/hub-config/tasks.json) that contains the information  for a particular optional target:
```json
"horizon": {
              "required": null,
              "optional": null
            }
```
and the tasks.json passes the validation without issues:
```
✔ Successfully validated config file ./flu-scenario-modeling-hub/hub-config/tasks.json against schema <https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/schemas/main/v2.0.0/tasks-schema.json>
[1] TRUE
attr(,"config_path")
./flu-scenario-modeling-hub/hub-config/tasks.json
attr(,"schema_version")
[1] "v2.0.0"
attr(,"schema_url")
https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/schemas/main/v2.0.0/tasks-schema.json
```
For additional information, the target has no horizon information (no date). 

However when I try to reproduce the json with the `hubUtils::create_task_id()` function, I have an error:
``` r
hubUtils::create_task_id("horizon", required = NULL, optional = NULL)
#> Error in `check_prop_not_all_null()`:
#> ✖ Both arguments `required` and `optional` cannot be NULL.
#> Backtrace:
#>     ▆
#>  1. └─hubUtils::create_task_id("horizon", required = NULL, optional = NULL)
#>  2.   └─hubUtils:::check_prop_not_all_null(required, optional)
#>  3.     └─cli::cli_abort(c(x = "Both arguments {.arg required} and {.arg optional}\n              cannot be NULL."))
#>  4.       └─rlang::abort(...)
```
<sup>Created on 2023-11-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The function documentation indicates that both cannot NULL so I am not sure on which is incorrect?

**Comment by elray1** [comment]
Here's an artificial/simple example with my understanding of the issue:  We have a hub with two task ids:

1. `target`, with two targets, `"a"` and `"b"`
2. `target_a_subtask`, which specifies some further refinement that's only relevant when `target == "a"`

The question is what to list for the optional and required values for the `target_a_subtask` column for the rows with `target == "b"`, where that value is not relevant. My take is that it would be good to specify _something_, so that all submission files do the same thing.

If we'd like submissions for target b to be required, we could maybe do something like:
```
...
  "rounds": [
    {
      ...
      "model_tasks": [
        {
          "task_ids": {
            "target": {
              "required": ["a"],
              "optional": null
            },
            "target_a_subtask": {
              "required": ["req1", "req2"],
              "optional": ["opt3", "opt4"]
            }
          }
        },
        {
          "task_ids": {
            "target": {
              "required": ["b"],
              "optional": null
            },
            "target_a_subtask": {
              "required": [""],
              "optional": null
            }
          }
        },
      ]
      ...
```

Where I am not totally sure that works, but the idea is that we are requiring submissions for target b, with an empty string in the `target_a_subtask` column for that target.  If empty strings are not consistently interpretable, maybe we would need to have `"required": ["NA"]`, and submission files would have to put `"NA"` in their files.

Or if submission for target b is optional, either/both of the entries under that target group could be moved from `"required"` to `"optional"`.

If we instead list
```
...
  "rounds": [
    {
      ...
      "model_tasks": [
        {
          "task_ids": {
            "target": {
              "required": ["a"],
              "optional": null
            },
            "target_a_subtask": {
              "required": ["req1", "req2"],
              "optional": ["opt3", "opt4"]
            }
          }
        },
        {
          "task_ids": {
            "target": {
              "required": ["b"],
              "optional": null
            },
            "target_a_subtask": {
              "required": null,
              "optional": null
            }
          }
        },
      ]
      ...
```

my question is what value are we expecting to see in the `target_a_subtask` column for rows where `target == "b"`?  We could maybe have a convention that this is to be interpreted as equivalent to the above, with either a `""` or an `"NA"` entry under `"required"`, so that the requirement status for that target group as a whole is determined by whether or not `["b"]` shows up under `"required"` or `"optional"`?

**Comment by annakrystalli** [comment]
Hey @LucieContamin ! 

Re the concerns regarding `NA`s as config task ID values.

If the `"NA"` which needs to be treated as character is part of a character array with other values, it will correctly be read in as `"NA"` from JSON. It only gets converted to `NA` when is is the only value in an array as is effectively unboxed when read in.

``` r
jsonlite::fromJSON('{"required": ["NA"]}')
#> $required
#> [1] NA
jsonlite::fromJSON('{"required": ["NA", "MA"]}')
#> $required
#> [1] "NA" "MA"
```

<sup>Created on 2024-03-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I have not found a quick solution to the situation where an `"NA"` character code is the only value in the array so this could indeed be problematic in this rare situation. Potentially there might be workarounds we could develop if necessary though.

Regarding the `NA`s and python, that's a very interesting topic indeed but I don't think it's specific to this issue as we already use `NA`s in our median and mean output type ID specifications. This may well be a bridge we have to cross more generally though when python versions of our tools are developed.

Finally re: `NA`s in `required` vs `optional`, what you describes indeed makes sense to me. I kinda feels it might be a good idea to have a whole page in our hubDocs about this topic!

**Comment by annakrystalli** [comment]
I'm now actually changing my mind about `"NA"` because it would cause problems when validating the config of non-character task IDs and we don't want all task IDs to also possibly be character to accomodate the potential for `"NA"` as that sort of makes the whole data type checking redundant/weaker.

Instead what I propose is that we indeed use `null` for both `required` and `optional` and handle that internally. I.e. where the expand grid function is failing in https://github.com/Infectious-Disease-Modeling-Hubs/hubValidations/issues/75 , if both `required` and `optional` are NULL when the config is read in, it would convert the value of `required` to `NA`.

I feel in the end this is the cleanest way and get's round both the `"NA"` as a task ID value and configs in python issue too.

**Comment by LucieContamin** [comment]
It sounds good. I think it makes sense.

**Comment by annakrystalli** [comment]
Great. If I made a start on implementing it, would you help me with documenting it?

**Comment by LucieContamin** [comment]
sure!

**Comment by kjsato** [comment]
@annakrystalli thanks for informing, I would appreciate it if you would update it!
